frontend:
  - changed-files:
    - any-glob-to-any-file: frontend/**

backend:
  - changed-files:
    - any-glob-to-any-file: backend/**

agendas:
  - changed-files:
    - any-glob-to-any-file: Agendas/**
