set shell := ["bash", "-cu"]
set windows-shell := ["powershell.exe", "-NoProfile", "-Command"]

check:
    uv run ruff check

fix:
    uv run ruff check --fix

test:
    uv run pytest -v

sync:
    uv sync

[windows]
run env:
    $env:ENV="{{env}}"; uv run fastapi dev

[unix]
run env:
    ENV={{env}} uv run fastapi dev