name: Bug Report
description: Issue for reporting bugs.
title: "[Bug] - <ADD TITLE HERE>"
labels: ["bug"]
projects: ["spe-uob/2025-ContinuousAssessment"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following information regarding your issue. Please take your time and include as much detail as possible, as it will help everyone that works on it.
  - type: textarea
    id: feature-details
    attributes:
      label: "Bug Details"
      description: "Describe the details of the bug you are reporting. Include the actual and expected behaviour. "
      placeholder: "The bug is..."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Reproduction Steps"
      description: "Describes the steps needed to be taken to reproduce the bug. This is crucial!"
      placeholder: "The steps to reproduce this bug are..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment Details"
      description: "Please provide information about the environment that the bug occurred in. This includes browser, version, operating system etc."
      placeholder: "The environment details are..."
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: error-log
    attributes:
      label: "Error logs"
      description: "If applicable, copy and paste the error logs that were displayed. This would be the Spring logs for backend, or the Browser console / terminal logs for frontend."
      render: shell
      placeholder: "Error logs..."
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional Information"
      description: "Describe any additional information required. "
      placeholder: "Additional information..."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Tasks that must be completed before submitting issue"
      options:
        - label: "I have added a comprehensive description of my issue and filled out all relevant fields."
          required: true
        - label: "I have added all metadata, labels, assignees, project, milestones, dates etc."
          required: true
        - label: "I have ensured that the issue is reproducible using the instructions I have provided."
