#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.mvc.problemdetails.enabled=true
server.error.include-stacktrace=never
server.error.include-binding-errors=never
server.error.include-message=never
error.handling.http-status-in-json-response=true

logging.level.org.springframework.boot.docker.compose=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

#docker compose settings
#the spring boot have the auto config support for the docker compose
#this hopefully will create the database and manage the life cycle of it
#there is also some support for change file and setting in the command line
#not sure whether they will work (hopefully)
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:true}
spring.docker.compose.file=${SPRING_DOCKER_COMPOSE_FILE:docker-compose.yaml}
spring.docker.compose.lifecycle-management=${SPRING_DOCKER_COMPOSE_LIFECYCLE:start_and_stop}
spring.docker.compose.readiness.timeout=${SPRING_DOCKER_COMPOSE_TIMEOUT:2m}

#spring.datasource.url=jdbc:postgresql://localhost:5432/carc_db
#spring.datasource.username=test
#spring.datasource.password=test
#spring.datasource.driver-class-name=org.postgresql.Driver

#JPA settings
#pring sql to console (test use)
spring.jpa.show-sql=true
#console output format (test use)
spring.jpa.properties.hibernate.format_sql=true
#close sql auto table creation
spring.jpa.hibernate.ddl-auto=none

#flyway settings
#A database version control tool
spring.flyway.enabled=false
spring.flyway.locations=classpath:database/migration
#setting that can use the old database that not create by flyway
#for now enable for easy testing the database
spring.flyway.baseline-on-migrate=true